import type { Category } from "@/lib/types";

export const area: Category = {
  id: "area",
  name: "Area",
  icon: "⬜",
  baseUnitId: "square-meters",
  units: [
    {
      id: "square-millimeters",
      name: "Square Millimeters",
      symbol: "mm²",
      factor: 0.000001,
      precision: "exact",
      formulaToBase: "value × 0.000001",
      source: "SI definition",
    },
    {
      id: "square-centimeters",
      name: "Square Centimeters",
      symbol: "cm²",
      factor: 0.0001,
      precision: "exact",
      formulaToBase: "value × 0.0001",
      source: "SI definition",
    },
    {
      id: "square-meters",
      name: "Square Meters",
      symbol: "m²",
      factor: 1,
      precision: "exact",
      formulaToBase: "value × 1",
      source: "SI derived unit",
    },
    {
      id: "square-kilometers",
      name: "Square Kilometers",
      symbol: "km²",
      factor: 1000000,
      precision: "exact",
      formulaToBase: "value × 1000000",
      source: "SI definition",
    },
    {
      id: "square-inches",
      name: "Square Inches",
      symbol: "in²",
      factor: 0.00064516,
      precision: "exact",
      formulaToBase: "value × 0.00064516",
      source: "International inch definition",
    },
    {
      id: "square-feet",
      name: "Square Feet",
      symbol: "ft²",
      factor: 0.09290304,
      precision: "exact",
      formulaToBase: "value × 0.09290304",
      source: "International foot definition",
    },
    {
      id: "square-yards",
      name: "Square Yards",
      symbol: "yd²",
      factor: 0.83612736,
      precision: "exact",
      formulaToBase: "value × 0.83612736",
      source: "International yard definition",
    },
    {
      id: "square-miles",
      name: "Square Miles",
      symbol: "mi²",
      factor: 2589988.110336,
      precision: "exact",
      formulaToBase: "value × 2589988.110336",
      source: "International mile definition",
    },
    {
      id: "acres",
      name: "Acres",
      symbol: "ac",
      factor: 4046.8564224,
      precision: "exact",
      formulaToBase: "value × 4046.8564224",
      source: "International yard and pound agreement, 1959",
    },
    {
      id: "hectares",
      name: "Hectares",
      symbol: "ha",
      factor: 10000,
      precision: "exact",
      formulaToBase: "value × 10000",
      source: "SI accepted unit",
    },
    {
      id: "ares",
      name: "Ares",
      symbol: "a",
      factor: 100,
      precision: "exact",
      formulaToBase: "value × 100",
      source: "SI accepted unit",
    },
  ],
};
