import type { Category } from "@/lib/types";

export const area: Category = {
  id: "area",
  name: "Area",
  icon: "⬜",
  baseUnitId: "square-meters",
  units: [
    {
      id: "square-millimeters",
      name: "Square Millimetres",
      symbol: "mm²",
      factor: 0.000001,
      precision: "exact",
      formulaToBase: "value × 0.000001",
      source: "SI definition",
    },
    {
      id: "square-centimeters",
      name: "Square Centimetres",
      symbol: "cm²",
      factor: 0.0001,
      precision: "exact",
      formulaToBase: "value × 0.0001",
      source: "SI definition",
    },
    {
      id: "square-meters",
      name: "Square Metres",
      symbol: "m²",
      factor: 1,
      precision: "exact",
      formulaToBase: "value × 1",
      source: "SI derived unit",
    },
    {
      id: "square-kilometers",
      name: "Square Kilometres",
      symbol: "km²",
      factor: 1000000,
      precision: "exact",
      formulaToBase: "value × 1000000",
      source: "SI definition",
    },
    {
      id: "square-inches",
      name: "Square Inches",
      symbol: "in²",
      factor: 0.00064516,
      precision: "exact",
      formulaToBase: "value × 0.00064516",
      source: "International inch definition",
    },
    {
      id: "square-feet",
      name: "Square Feet",
      symbol: "ft²",
      factor: 0.09290304,
      precision: "exact",
      formulaToBase: "value × 0.09290304",
      source: "International foot definition",
    },
    {
      id: "square-yards",
      name: "Square Yards",
      symbol: "yd²",
      factor: 0.83612736,
      precision: "exact",
      formulaToBase: "value × 0.83612736",
      source: "International yard definition",
    },
    {
      id: "square-miles",
      name: "Square Miles",
      symbol: "mi²",
      factor: 2589988.110336,
      precision: "exact",
      formulaToBase: "value × 2589988.110336",
      source: "International mile definition",
    },
    {
      id: "acres",
      name: "Acres",
      symbol: "ac",
      factor: 4046.8564224,
      precision: "exact",
      formulaToBase: "value × 4046.8564224",
      source: "International yard and pound agreement, 1959",
    },
    {
      id: "hectares",
      name: "Hectares",
      symbol: "ha",
      factor: 10000,
      precision: "exact",
      formulaToBase: "value × 10000",
      source: "SI accepted unit",
    },
    {
      id: "ares",
      name: "Ares",
      symbol: "a",
      factor: 100,
      precision: "exact",
      formulaToBase: "value × 100",
      source: "SI accepted unit",
    },
    {
      id: "dunam",
      name: "Dunam (Metric)",
      symbol: "dunam",
      factor: 1000,
      precision: "exact",
      formulaToBase: "value × 1000",
      source: "Old Ottoman unit, redefined metric",
    },
    {
      id: "tsubo",
      name: "Tsubo",
      symbol: "tsubo",
      factor: 3.305785,
      precision: "approximate",
      formulaToBase: "value × 3.306",
      source: "Japanese measurement law",
    },
     {
       id: "barns",
       name: "Barns",
       symbol: "b",
       factor: 1e-28,
       precision: "exact",
       formulaToBase: "value × 10⁻²⁸",
       source: "Nuclear physics unit",
     },
    {
      id: "chinese-mu",
      name: "Chinese Mǔ",
      symbol: "mǔ",
      factor: 666.6667,
      precision: "approximate",
      formulaToBase: "value × 666.6667",
      source: "PRC standard: 1 mǔ ≈ 666.67 m²",
    },
    {
      id: "korean-pyeong",
      name: "Korean Pyeong",
      symbol: "pyeong",
      factor: 3.305785,
      precision: "approximate",
      formulaToBase: "value × 3.305785",
      source: "Korean: 1 pyeong ≈ 3.306 m² (same definition as tsubo)",
    },
    {
      id: "indian-bigha",
      name: "Indian Bigha",
      symbol: "bigha",
      factor: 2529.285,
      precision: "approximate",
      formulaToBase: "value × 2529.285",
      source: "Standard bigha (UP/Bihar): 1 bigha ≈ 2529.3 m²",
    },
    {
      id: "thai-rai",
      name: "Thai Rai",
      symbol: "rai",
      factor: 1600,
      precision: "exact",
      formulaToBase: "value × 1600",
      source: "Thai Royal Institute: 1 rai = 1600 m²",
    },
    {
      id: "vietnamese-mau",
      name: "Vietnamese Mẫu",
      symbol: "mẫu",
      factor: 1000,
      precision: "exact",
      formulaToBase: "value × 1000",
      source: "Vietnamese traditional unit: 1 mẫu = 1000 m²",
    },
   ],
};
