import type { Category } from "@/lib/types";

export const cooking: Category = {
  id: "cooking",
  name: "Cooking Volume",
  icon: "🍳",
  baseUnitId: "milliliters-cooking",
  units: [
    {
      id: "milliliters-cooking",
      name: "Millilitres",
      symbol: "mL",
      factor: 1,
      precision: "exact",
      formulaToBase: "value × 1",
      source: "SI definition",
    },
    {
      id: "metric-teaspoons",
      name: "Metric Teaspoons",
      symbol: "tsp",
      factor: 5,
      precision: "exact",
      formulaToBase: "value × 5",
      source: "International metric teaspoon = 5 mL",
    },
    {
      id: "dessert-spoons",
      name: "Dessert Spoons",
      symbol: "dsp",
      factor: 10,
      precision: "exact",
      formulaToBase: "value × 10",
      source: "Metric dessert spoon = 10 mL",
    },
    {
      id: "metric-tablespoons",
      name: "Metric Tablespoons",
      symbol: "tbsp",
      factor: 15,
      precision: "exact",
      formulaToBase: "value × 15",
      source: "International metric tablespoon = 15 mL",
    },
    {
      id: "australian-tablespoons",
      name: "Australian Tablespoons",
      symbol: "tbsp (AU)",
      factor: 20,
      precision: "exact",
      formulaToBase: "value × 20",
      source: "Australian standard: 1 tbsp = 20 mL",
    },
    {
      id: "japanese-cups",
      name: "Japanese Cups",
      symbol: "cup (JP)",
      factor: 200,
      precision: "exact",
      formulaToBase: "value × 200",
      source: "Japanese cooking standard: 1 cup = 200 mL",
    },
    {
      id: "metric-cups",
      name: "Metric Cups",
      symbol: "cup",
      factor: 250,
      precision: "exact",
      formulaToBase: "value × 250",
      source: "International metric cup = 250 mL",
    },
    {
      id: "drops",
      name: "Drops",
      symbol: "gtt",
      factor: 0.05,
      precision: "approximate",
      formulaToBase: "value × 0.05",
      source: "Medical/pharmacological standard drop ≈ 0.05 mL",
    },
    {
      id: "pinches",
      name: "Pinches",
      symbol: "pinch",
      factor: 0.31,
      precision: "approximate",
      formulaToBase: "value × 0.31",
      source: "Approximate: 1 pinch ≈ 1/16 tsp ≈ 0.31 mL",
    },
  ],
};
