import type { Category } from "@/lib/types";

export const dataRate: Category = {
  id: "data-rate",
  name: "Data Rate",
  icon: "📡",
  baseUnitId: "bits-per-second",
  units: [
    {
      id: "bits-per-second",
      name: "Bits per Second",
      symbol: "bps",
      factor: 1,
      precision: "exact",
      formulaToBase: "value × 1",
      source: "Category base unit",
    },
    {
      id: "kilobits-per-second",
      name: "Kilobits per Second",
      symbol: "Kbps",
      factor: 1000,
      precision: "exact",
      formulaToBase: "value × 1000",
      source: "SI decimal prefix",
    },
    {
      id: "megabits-per-second",
      name: "Megabits per Second",
      symbol: "Mbps",
      factor: 1000000,
      precision: "exact",
      formulaToBase: "value × 1000000",
      source: "SI decimal prefix",
    },
    {
      id: "gigabits-per-second",
      name: "Gigabits per Second",
      symbol: "Gbps",
      factor: 1000000000,
      precision: "exact",
      formulaToBase: "value × 1000000000",
      source: "SI decimal prefix",
    },
    {
      id: "bytes-per-second",
      name: "Bytes per Second",
      symbol: "B/s",
      factor: 8,
      precision: "exact",
      formulaToBase: "value × 8",
      source: "By definition: 1 byte = 8 bits",
    },
    {
      id: "kilobytes-per-second",
      name: "Kilobytes per Second",
      symbol: "KB/s",
      factor: 8000,
      precision: "exact",
      formulaToBase: "value × 8000",
      source: "SI decimal prefix and byte definition",
    },
    {
      id: "megabytes-per-second",
      name: "Megabytes per Second",
      symbol: "MB/s",
      factor: 8000000,
      precision: "exact",
      formulaToBase: "value × 8000000",
      source: "SI decimal prefix and byte definition",
    },
    {
      id: "gigabytes-per-second",
      name: "Gigabytes per Second",
      symbol: "GB/s",
      factor: 8000000000,
      precision: "exact",
      formulaToBase: "value × 8000000000",
      source: "SI decimal prefix and byte definition",
    },
  ],
};
