import type { Category } from "@/lib/types";

export const digitalStorage: Category = {
  id: "digital-storage",
  name: "Digital Storage",
  icon: "💾",
  baseUnitId: "bytes",
  units: [
    {
      id: "bits",
      name: "Bits",
      symbol: "b",
      factor: 0.125,
      precision: "exact",
      formulaToBase: "value × 0.125",
      source: "By definition: 8 bits = 1 byte",
    },
    {
      id: "bytes",
      name: "Bytes",
      symbol: "B",
      factor: 1,
      precision: "exact",
      formulaToBase: "value × 1",
      source: "Category base unit",
    },
    {
      id: "kilobytes",
      name: "Kilobytes",
      symbol: "kB",
      factor: 1000,
      precision: "exact",
      formulaToBase: "value × 1000",
      source: "SI decimal prefix",
    },
    {
      id: "megabytes",
      name: "Megabytes",
      symbol: "MB",
      factor: 1000000,
      precision: "exact",
      formulaToBase: "value × 1000000",
      source: "SI decimal prefix",
    },
    {
      id: "gigabytes",
      name: "Gigabytes",
      symbol: "GB",
      factor: 1000000000,
      precision: "exact",
      formulaToBase: "value × 1000000000",
      source: "SI decimal prefix",
    },
    {
      id: "terabytes",
      name: "Terabytes",
      symbol: "TB",
      factor: 1000000000000,
      precision: "exact",
      formulaToBase: "value × 1000000000000",
      source: "SI decimal prefix",
    },
    {
      id: "kibibytes",
      name: "Kibibytes",
      symbol: "KiB",
      factor: 1024,
      precision: "exact",
      formulaToBase: "value × 1024",
      source: "IEC binary prefix",
    },
    {
      id: "mebibytes",
      name: "Mebibytes",
      symbol: "MiB",
      factor: 1048576,
      precision: "exact",
      formulaToBase: "value × 1048576",
      source: "IEC binary prefix",
    },
    {
      id: "gibibytes",
      name: "Gibibytes",
      symbol: "GiB",
      factor: 1073741824,
      precision: "exact",
      formulaToBase: "value × 1073741824",
      source: "IEC binary prefix",
    },
    {
      id: "tebibytes",
      name: "Tebibytes",
      symbol: "TiB",
      factor: 1099511627776,
      precision: "exact",
      formulaToBase: "value × 1099511627776",
      source: "IEC binary prefix",
    },
    {
      id: "petabytes",
      name: "Petabytes",
      symbol: "PB",
      factor: 1e15,
      precision: "exact",
      formulaToBase: "value × 1e15",
      source: "SI decimal prefix",
    },
    {
      id: "pebibytes",
      name: "Pebibytes",
      symbol: "PiB",
      factor: 1125899906842624,
      precision: "exact",
      formulaToBase: "value × 1125899906842624",
      source: "IEC binary prefix: 2⁵⁰",
    },
  ],
};
