import type { Category } from "@/lib/types";

export const energy: Category = {
  id: "energy",
  name: "Energy",
  icon: "⚡",
  baseUnitId: "joules",
  units: [
    {
      id: "joules",
      name: "Joules",
      symbol: "J",
      factor: 1,
      precision: "exact",
      formulaToBase: "value × 1",
      source: "SI derived unit",
    },
    {
      id: "kilojoules",
      name: "Kilojoules",
      symbol: "kJ",
      factor: 1000,
      precision: "exact",
      formulaToBase: "value × 1000",
      source: "SI definition",
    },
    {
      id: "megajoules",
      name: "Megajoules",
      symbol: "MJ",
      factor: 1000000,
      precision: "exact",
      formulaToBase: "value × 1000000",
      source: "SI definition",
    },
    {
      id: "watt-hours",
      name: "Watt-hours",
      symbol: "Wh",
      factor: 3600,
      precision: "exact",
      formulaToBase: "value × 3600",
      source: "1 Wh = 3600 J",
    },
    {
      id: "kilowatt-hours",
      name: "Kilowatt-hours",
      symbol: "kWh",
      factor: 3600000,
      precision: "exact",
      formulaToBase: "value × 3600000",
      source: "1 kWh = 3,600,000 J",
    },
    {
      id: "calories",
      name: "Calories",
      symbol: "cal",
      factor: 4.184,
      precision: "exact",
      formulaToBase: "value × 4.184",
      source: "Thermochemical calorie definition",
    },
    {
      id: "kilocalories",
      name: "Kilocalories",
      symbol: "kcal",
      factor: 4184,
      precision: "exact",
      formulaToBase: "value × 4184",
      source: "By definition: 1 kcal = 1000 cal",
    },
    {
      id: "btu",
      name: "British Thermal Units",
      symbol: "BTU",
      factor: 1055.05585262,
      precision: "approximate",
      formulaToBase: "value × 1055.05585262",
      source: "BTU (IT) conversion",
    },
    {
      id: "therms",
      name: "Therms",
      symbol: "therm",
      factor: 105505585.262,
      precision: "approximate",
      formulaToBase: "value × 105505585.262",
      source: "1 therm = 100,000 BTU (IT)",
    },
    {
      id: "electronvolts",
      name: "Electronvolts",
      symbol: "eV",
      factor: 1.602176634e-19,
      precision: "exact",
      formulaToBase: "value × 1.602176634e-19",
      source: "SI definition of elementary charge",
    },
  ],
};
