import type { Category } from "@/lib/types";

export const force: Category = {
  id: "force",
  name: "Force",
  icon: "💪",
  baseUnitId: "newtons",
  units: [
    {
      id: "newtons",
      name: "Newtons",
      symbol: "N",
      factor: 1,
      precision: "exact",
      formulaToBase: "value × 1",
      source: "SI derived unit",
    },
    {
      id: "kilonewtons",
      name: "Kilonewtons",
      symbol: "kN",
      factor: 1000,
      precision: "exact",
      formulaToBase: "value × 1000",
      source: "SI definition",
    },
    {
      id: "dynes",
      name: "Dynes",
      symbol: "dyn",
      factor: 0.00001,
      precision: "exact",
      formulaToBase: "value × 0.00001",
      source: "CGS system definition",
    },
    {
      id: "kilogram-force",
      name: "Kilogram-force",
      symbol: "kgf",
      factor: 9.80665,
      precision: "exact",
      formulaToBase: "value × 9.80665",
      source: "Conventional standard gravity",
    },
    {
      id: "pounds-force",
      name: "Pounds-force",
      symbol: "lbf",
      factor: 4.4482216152605,
      precision: "exact",
      formulaToBase: "value × 4.4482216152605",
      source: "International yard and pound agreement, 1959",
    },
    {
      id: "kips",
      name: "Kips",
      symbol: "kip",
      factor: 4448.221615,
      precision: "approximate",
      formulaToBase: "value × 4448.221615",
      source: "By definition: 1 kip = 1000 lbf",
    },
  ],
};
