import type { Category } from "@/lib/types";

export const length: Category = {
  id: "length",
  name: "Length & Distance",
  icon: "📏",
  baseUnitId: "meters",
  units: [
    {
      id: "micrometers",
      name: "Micrometres",
      symbol: "µm",
      factor: 0.000001,
      precision: "exact",
      formulaToBase: "value × 0.000001",
      source: "SI definition (micro prefix)",
    },
    {
      id: "nanometers",
      name: "Nanometres",
      symbol: "nm",
      factor: 0.000000001,
      precision: "exact",
      formulaToBase: "value × 0.000000001",
      source: "SI definition (nano prefix)",
    },
    {
      id: "millimeters",
      name: "Millimetres",
      symbol: "mm",
      factor: 0.001,
      precision: "exact",
      formulaToBase: "value × 0.001",
      source: "SI definition (milli prefix)",
    },
    {
      id: "centimeters",
      name: "Centimetres",
      symbol: "cm",
      factor: 0.01,
      precision: "exact",
      formulaToBase: "value × 0.01",
      source: "SI definition (centi prefix)",
    },
    {
      id: "meters",
      name: "Metres",
      symbol: "m",
      factor: 1,
      precision: "exact",
      formulaToBase: "value × 1",
      source: "SI base unit",
    },
    {
      id: "kilometers",
      name: "Kilometres",
      symbol: "km",
      factor: 1000,
      precision: "exact",
      formulaToBase: "value × 1000",
      source: "SI definition (kilo prefix)",
    },
    {
      id: "inches",
      name: "Inches",
      symbol: "in",
      factor: 0.0254,
      precision: "exact",
      formulaToBase: "value × 0.0254",
      source: "International yard and pound agreement, 1959",
    },
    {
      id: "feet",
      name: "Feet",
      symbol: "ft",
      factor: 0.3048,
      precision: "exact",
      formulaToBase: "value × 0.3048",
      source: "International yard and pound agreement, 1959",
    },
    {
      id: "yards",
      name: "Yards",
      symbol: "yd",
      factor: 0.9144,
      precision: "exact",
      formulaToBase: "value × 0.9144",
      source: "International yard and pound agreement, 1959",
    },
    {
      id: "miles",
      name: "Miles",
      symbol: "mi",
      factor: 1609.344,
      precision: "exact",
      formulaToBase: "value × 1609.344",
      source: "International yard and pound agreement, 1959",
    },
    {
      id: "nautical-miles",
      name: "Nautical Miles",
      symbol: "nmi",
      factor: 1852,
      precision: "exact",
      formulaToBase: "value × 1852",
      source: "By definition: 1 nmi = 1852 m",
    },
    {
      id: "mils",
      name: "Mils (Thou)",
      symbol: "mil",
      factor: 0.0000254,
      precision: "exact",
      formulaToBase: "value × 0.0000254",
      source: "1 mil = 0.001 inch, international inch definition",
    },
    {
      id: "hands",
      name: "Hands",
      symbol: "hh",
      factor: 0.1016,
      precision: "exact",
      formulaToBase: "value × 0.1016",
      source: "1 hand = 4 inches, international inch definition",
    },
    {
      id: "fathoms",
      name: "Fathoms",
      symbol: "ftm",
      factor: 1.8288,
      precision: "exact",
      formulaToBase: "value × 1.8288",
      source: "1 fathom = 6 feet, international foot definition",
    },
    {
      id: "chains",
      name: "Chains",
      symbol: "ch",
      factor: 20.1168,
      precision: "exact",
      formulaToBase: "value × 20.1168",
      source: "1 chain = 66 feet, international foot definition",
    },
    {
      id: "furlongs",
      name: "Furlongs",
      symbol: "fur",
      factor: 201.168,
      precision: "exact",
      formulaToBase: "value × 201.168",
      source: "1 furlong = 10 chains",
    },
    {
      id: "astronomical-units",
      name: "Astronomical Units",
      symbol: "AU",
      factor: 149597870700,
      precision: "exact",
      formulaToBase: "value × 149597870700",
      source: "IAU 2012 Resolution B2",
    },
    {
      id: "light-years",
      name: "Light Years",
      symbol: "ly",
      factor: 9460730472580800,
      precision: "exact",
      formulaToBase: "value × 9.461e+15",
      source: "IAU definition",
    },
    {
      id: "parsecs",
      name: "Parsecs",
      symbol: "pc",
      factor: 3.08567758149137e16,
      precision: "approximate",
      formulaToBase: "value × 3.086e+16",
      source: "IAU 2015 Resolution B2",
    },
    {
      id: "angstroms",
      name: "Angstroms",
      symbol: "Å",
      factor: 1e-10,
      precision: "exact",
      formulaToBase: "value × 1e-10",
      source: "SI accepted unit",
    },
    {
      id: "chinese-li",
      name: "Chinese Li (Modern)",
      symbol: "li",
      factor: 500,
      precision: "exact",
      formulaToBase: "value × 500",
      source: "Market definition (PRC)",
    },
    {
      id: "japanese-shaku",
      name: "Japanese Shaku",
      symbol: "shaku",
      factor: 0.303030303030303,
      precision: "approximate",
      formulaToBase: "value × 0.303 (10/33 m)",
      source: "Japanese measurement law (10/33 m)",
    },
    {
      id: "japanese-sun",
      name: "Japanese Sun",
      symbol: "sun",
      factor: 0.0303030303030303,
      precision: "approximate",
      formulaToBase: "value × 0.0303 (1/33 m)",
      source: "Japanese measurement law (1/33 m)",
    },
  ],
};
