import type { Category } from "@/lib/types";

export const mass: Category = {
  id: "mass",
  name: "Mass & Weight",
  icon: "⚖️",
  baseUnitId: "grams",
  units: [
    {
      id: "micrograms",
      name: "Micrograms",
      symbol: "µg",
      factor: 0.000001,
      precision: "exact",
      formulaToBase: "value × 0.000001",
      source: "SI definition",
    },
    {
      id: "milligrams",
      name: "Milligrams",
      symbol: "mg",
      factor: 0.001,
      precision: "exact",
      formulaToBase: "value × 0.001",
      source: "SI definition",
    },
    {
      id: "grams",
      name: "Grams",
      symbol: "g",
      factor: 1,
      precision: "exact",
      formulaToBase: "value × 1",
      source: "SI definition",
    },
    {
      id: "kilograms",
      name: "Kilograms",
      symbol: "kg",
      factor: 1000,
      precision: "exact",
      formulaToBase: "value × 1000",
      source: "SI base unit scaling",
    },
    {
      id: "metric-tonnes",
      name: "Metric Tonnes",
      symbol: "t",
      factor: 1000000,
      precision: "exact",
      formulaToBase: "value × 1000000",
      source: "SI accepted unit",
    },
    {
      id: "ounces",
      name: "Ounces",
      symbol: "oz",
      factor: 28.349523125,
      precision: "exact",
      formulaToBase: "value × 28.349523125",
      source: "International yard and pound agreement, 1959",
    },
    {
      id: "pounds",
      name: "Pounds",
      symbol: "lb",
      factor: 453.59237,
      precision: "exact",
      formulaToBase: "value × 453.59237",
      source: "International yard and pound agreement, 1959",
    },
    {
      id: "stones",
      name: "Stones",
      symbol: "st",
      factor: 6350.29318,
      precision: "exact",
      formulaToBase: "value × 6350.29318",
      source: "By definition: 1 st = 14 lb",
    },
    {
      id: "short-tons",
      name: "Short Tons",
      symbol: "ton (US)",
      factor: 907184.74,
      precision: "exact",
      formulaToBase: "value × 907184.74",
      source: "By definition: 1 short ton = 2000 lb",
    },
    {
      id: "long-tons",
      name: "Long Tons",
      symbol: "long ton",
      factor: 1016046.9088,
      precision: "exact",
      formulaToBase: "value × 1016046.9088",
      source: "By definition: 1 long ton = 2240 lb",
    },
    {
      id: "troy-ounces",
      name: "Troy Ounces",
      symbol: "ozt",
      factor: 31.1034768,
      precision: "exact",
      formulaToBase: "value × 31.1034768",
      source: "Troy system definition",
    },
    {
      id: "grains",
      name: "Grains",
      symbol: "gr",
      factor: 0.06479891,
      precision: "exact",
      formulaToBase: "value × 0.06479891",
      source: "By definition: 1 grain = 64.79891 mg",
    },
    {
      id: "carats",
      name: "Carats",
      symbol: "ct",
      factor: 0.2,
      precision: "exact",
      formulaToBase: "value × 0.2",
      source: "Metric carat definition",
    },
    {
      id: "metric-quintals",
      name: "Metric Quintals",
      symbol: "q",
      factor: 100000,
      precision: "exact",
      formulaToBase: "value × 100000",
      source: "Metric definition (100 kg)",
    },
    {
      id: "catty-china",
      name: "Catty (China)",
      symbol: "jin",
      factor: 500,
      precision: "exact",
      formulaToBase: "value × 500",
      source: "PRC market definition",
    },
    {
      id: "catty-hk",
      name: "Catty (HK)",
      symbol: "kan",
      factor: 604.78982,
      precision: "exact",
      formulaToBase: "value × 604.79",
      source: "Hong Kong Weights and Measures Ordinance",
    },
    {
      id: "tael-china",
      name: "Tael (China)",
      symbol: "liang",
      factor: 50,
      precision: "exact",
      formulaToBase: "value × 50",
      source: "PRC market definition (1/10 catty)",
    },
    {
      id: "tael-hk",
      name: "Tael (HK)",
      symbol: "tael",
      factor: 37.79936375,
      precision: "exact",
      formulaToBase: "value × 37.8 (1/16 HK catty)",
      source: "Hong Kong Weights and Measures Ordinance",
    },
    {
      id: "kan-japan",
      name: "Kan (Japan)",
      symbol: "kan",
      factor: 3750,
      precision: "exact",
      formulaToBase: "value × 3750",
      source: "Japanese measurement law",
    },
     {
       id: "picul-hk",
       name: "Picul (HK)",
       symbol: "tam",
       factor: 60478.982,
       precision: "exact",
       formulaToBase: "value × 60478.98",
       source: "Hong Kong Weights and Measures Ordinance (100 catties)",
     },
     {
       id: "indian-tola",
       name: "Indian Tola",
       symbol: "tola",
       factor: 11.6638,
       precision: "exact",
       formulaToBase: "value × 11.6638",
       source: "Indian Standards: 1 tola = 11.6638 g",
     },
     {
       id: "indian-seer",
       name: "Indian Seer",
       symbol: "seer",
       factor: 933.104,
       precision: "exact",
       formulaToBase: "value × 933.104",
       source: "Indian Standards: 1 seer = 80 tola = 933.104 g",
     },
     {
       id: "japanese-momme",
       name: "Japanese Momme",
       symbol: "匁",
       factor: 3.75,
       precision: "exact",
       formulaToBase: "value × 3.75",
       source: "Japanese Metrication Act 1891: 1 momme = 3.75 g",
     },
     {
       id: "thai-baht-mass",
       name: "Thai Baht (mass)",
       symbol: "baht",
       factor: 15.244,
       precision: "exact",
       formulaToBase: "value × 15.244",
       source: "Thai Royal Institute: 1 baht = 15.244 g",
     },
     {
       id: "pennyweights",
       name: "Pennyweights",
       symbol: "dwt",
       factor: 1.55517384,
       precision: "exact",
       formulaToBase: "value × 1.55517384",
       source: "Troy system: 1 dwt = 1/20 troy oz",
     },
     {
       id: "troy-pounds",
       name: "Troy Pounds",
       symbol: "lb t",
       factor: 373.2417216,
       precision: "exact",
       formulaToBase: "value × 373.2417216",
       source: "Troy system: 1 troy lb = 12 troy oz",
     },
   ],
};
