import type { Category } from "@/lib/types";

export const power: Category = {
  id: "power",
  name: "Power",
  icon: "🔌",
  baseUnitId: "watts",
  units: [
    {
      id: "watts",
      name: "Watts",
      symbol: "W",
      factor: 1,
      precision: "exact",
      formulaToBase: "value × 1",
      source: "SI derived unit",
    },
    {
      id: "kilowatts",
      name: "Kilowatts",
      symbol: "kW",
      factor: 1000,
      precision: "exact",
      formulaToBase: "value × 1000",
      source: "SI definition",
    },
    {
      id: "megawatts",
      name: "Megawatts",
      symbol: "MW",
      factor: 1000000,
      precision: "exact",
      formulaToBase: "value × 1000000",
      source: "SI definition",
    },
    {
      id: "mechanical-horsepower",
      name: "Mechanical Horsepower",
      symbol: "hp",
      factor: 745.699872,
      precision: "approximate",
      formulaToBase: "value × 745.699872",
      source: "Imperial mechanical horsepower",
    },
    {
      id: "metric-horsepower",
      name: "Metric Horsepower",
      symbol: "PS",
      factor: 735.49875,
      precision: "exact",
      formulaToBase: "value × 735.49875",
      source: "Metric horsepower definition",
    },
    {
      id: "btu-per-hour",
      name: "BTU per Hour",
      symbol: "BTU/h",
      factor: 0.2930710702,
      precision: "approximate",
      formulaToBase: "value × 0.2930710702",
      source: "From BTU (IT) per hour",
    },
    {
      id: "tons-of-refrigeration",
      name: "Tons of Refrigeration",
      symbol: "TR",
      factor: 3516.852842,
      precision: "approximate",
      formulaToBase: "value × 3516.852842",
      source: "HVAC convention: 12,000 BTU/h",
    },
  ],
};
