import type { Category } from "@/lib/types";

export const pressure: Category = {
  id: "pressure",
  name: "Pressure",
  icon: "🔵",
  baseUnitId: "pascals",
  units: [
    {
      id: "pascals",
      name: "Pascals",
      symbol: "Pa",
      factor: 1,
      precision: "exact",
      formulaToBase: "value × 1",
      source: "SI derived unit",
    },
    {
      id: "kilopascals",
      name: "Kilopascals",
      symbol: "kPa",
      factor: 1000,
      precision: "exact",
      formulaToBase: "value × 1000",
      source: "SI definition",
    },
    {
      id: "megapascals",
      name: "Megapascals",
      symbol: "MPa",
      factor: 1000000,
      precision: "exact",
      formulaToBase: "value × 1000000",
      source: "SI definition",
    },
    {
      id: "bar",
      name: "Bar",
      symbol: "bar",
      factor: 100000,
      precision: "exact",
      formulaToBase: "value × 100000",
      source: "Metric bar definition",
    },
    {
      id: "millibar",
      name: "Millibar",
      symbol: "mbar",
      factor: 100,
      precision: "exact",
      formulaToBase: "value × 100",
      source: "By definition: 1 mbar = 100 Pa",
    },
    {
      id: "psi",
      name: "Pounds per Square Inch",
      symbol: "psi",
      factor: 6894.757293,
      precision: "approximate",
      formulaToBase: "value × 6894.757293",
      source: "From lbf/in² using international inch and pound",
    },
    {
      id: "atmospheres",
      name: "Standard Atmospheres",
      symbol: "atm",
      factor: 101325,
      precision: "exact",
      formulaToBase: "value × 101325",
      source: "By definition: 1 atm = 101325 Pa",
    },
    {
      id: "torr",
      name: "Torr",
      symbol: "Torr",
      factor: 133.322368421,
      precision: "exact",
      formulaToBase: "value × 133.322368421",
      source: "By definition: 1 torr = 1/760 atm",
    },
    {
      id: "mmh2o",
      name: "Millimeters of Water",
      symbol: "mmH2O",
      factor: 9.80665,
      precision: "approximate",
      formulaToBase: "value × 9.80665",
      source: "Water column at standard gravity",
    },
  ],
};
