import type { Category } from "@/lib/types";

export const temperature: Category = {
  id: "temperature",
  name: "Temperature",
  icon: "🌡️",
  baseUnitId: "kelvin",
  units: [
    {
      id: "kelvin",
      name: "Kelvin",
      symbol: "K",
      toBase: (value) => value,
      fromBase: (value) => value,
      precision: "exact",
      formulaToBase: "value",
      source: "SI base unit",
    },
    {
      id: "celsius",
      name: "Celsius",
      symbol: "°C",
      toBase: (value) => value + 273.15,
      fromBase: (value) => value - 273.15,
      precision: "exact",
      formulaToBase: "value + 273.15",
      source: "ITS-90 / SI relation",
    },
    {
      id: "fahrenheit",
      name: "Fahrenheit",
      symbol: "°F",
      toBase: (value) => (value - 32) * (5 / 9) + 273.15,
      fromBase: (value) => (value - 273.15) * (9 / 5) + 32,
      precision: "exact",
      formulaToBase: "(value - 32) × 5/9 + 273.15",
      source: "Defined Fahrenheit to Celsius/Kelvin relation",
    },
    {
      id: "rankine",
      name: "Rankine",
      symbol: "°R",
      toBase: (value) => value * (5 / 9),
      fromBase: (value) => value * (9 / 5),
      precision: "exact",
      formulaToBase: "value × 5/9",
      source: "Rankine scale definition",
    },
    {
      id: "reaumur",
      name: "Réaumur",
      symbol: "°Ré",
      toBase: (value: number) => value * (5 / 4) + 273.15,
      fromBase: (value: number) => (value - 273.15) * (4 / 5),
      precision: "exact",
      formulaToBase: "value × 5/4 + 273.15",
      source: "Réaumur scale: 0°Ré = 0°C, 80°Ré = 100°C",
    },
    {
      id: "delisle",
      name: "Delisle",
      symbol: "°De",
      toBase: (value: number) => 373.15 - value * (2 / 3),
      fromBase: (value: number) => (373.15 - value) * (3 / 2),
      precision: "exact",
      formulaToBase: "373.15 − value × 2/3",
      source: "Delisle scale: 0°De = 100°C, 150°De = 0°C",
    },
  ],
};
