import type { Category } from "@/lib/types";

export const time: Category = {
  id: "time",
  name: "Time",
  icon: "⏱️",
  baseUnitId: "seconds",
  units: [
    {
      id: "nanoseconds",
      name: "Nanoseconds",
      symbol: "ns",
      factor: 0.000000001,
      precision: "exact",
      formulaToBase: "value × 0.000000001",
      source: "SI definition",
    },
    {
      id: "microseconds",
      name: "Microseconds",
      symbol: "µs",
      factor: 0.000001,
      precision: "exact",
      formulaToBase: "value × 0.000001",
      source: "SI definition",
    },
    {
      id: "milliseconds",
      name: "Milliseconds",
      symbol: "ms",
      factor: 0.001,
      precision: "exact",
      formulaToBase: "value × 0.001",
      source: "SI definition",
    },
    {
      id: "seconds",
      name: "Seconds",
      symbol: "s",
      factor: 1,
      precision: "exact",
      formulaToBase: "value × 1",
      source: "SI base unit",
    },
    {
      id: "minutes",
      name: "Minutes",
      symbol: "min",
      factor: 60,
      precision: "exact",
      formulaToBase: "value × 60",
      source: "Sexagesimal time definition",
    },
    {
      id: "hours",
      name: "Hours",
      symbol: "h",
      factor: 3600,
      precision: "exact",
      formulaToBase: "value × 3600",
      source: "By definition: 1 h = 3600 s",
    },
    {
      id: "days",
      name: "Days",
      symbol: "d",
      factor: 86400,
      precision: "exact",
      formulaToBase: "value × 86400",
      source: "By definition: 1 d = 24 h",
    },
    {
      id: "weeks",
      name: "Weeks",
      symbol: "wk",
      factor: 604800,
      precision: "exact",
      formulaToBase: "value × 604800",
      source: "By definition: 1 week = 7 days",
    },
    {
      id: "years",
      name: "Years (Julian)",
      symbol: "yr",
      factor: 31557600,
      precision: "exact",
      formulaToBase: "value × 31557600",
      source: "Julian year definition (365.25 days)",
    },
  ],
};
