import type { Category } from "@/lib/types";

export const torque: Category = {
  id: "torque",
  name: "Torque",
  icon: "🔧",
  baseUnitId: "newton-meters",
  units: [
    {
      id: "newton-meters",
      name: "Newton-metres",
      symbol: "N·m",
      factor: 1,
      precision: "exact",
      formulaToBase: "value × 1",
      source: "SI derived unit",
    },
    {
      id: "newton-centimeters",
      name: "Newton-centimetres",
      symbol: "N·cm",
      factor: 0.01,
      precision: "exact",
      formulaToBase: "value × 0.01",
      source: "SI scaling",
    },
    {
      id: "pound-force-inches",
      name: "Pound-force inches",
      symbol: "lbf·in",
      factor: 0.112984829,
      precision: "approximate",
      formulaToBase: "value × 0.112984829",
      source: "From lbf and inch definitions",
    },
    {
      id: "pound-force-feet",
      name: "Pound-force feet",
      symbol: "lbf·ft",
      factor: 1.355817948,
      precision: "approximate",
      formulaToBase: "value × 1.355817948",
      source: "From lbf and foot definitions",
    },
    {
      id: "kilogram-force-meters",
      name: "Kilogram-force metres",
      symbol: "kgf·m",
      factor: 9.80665,
      precision: "exact",
      formulaToBase: "value × 9.80665",
      source: "Conventional standard gravity",
    },
    {
      id: "kilogram-force-centimeters",
      name: "Kilogram-force centimetres",
      symbol: "kgf·cm",
      factor: 0.0980665,
      precision: "exact",
      formulaToBase: "value × 0.0980665",
      source: "Conventional standard gravity",
    },
  ],
};
