import type { Category } from "@/lib/types";

export const volume: Category = {
  id: "volume",
  name: "Volume & Capacity",
  icon: "🧊",
  baseUnitId: "liters",
  units: [
    {
      id: "milliliters",
      name: "Milliliters",
      symbol: "mL",
      factor: 0.001,
      precision: "exact",
      formulaToBase: "value × 0.001",
      source: "SI definition",
    },
    {
      id: "liters",
      name: "Liters",
      symbol: "L",
      factor: 1,
      precision: "exact",
      formulaToBase: "value × 1",
      source: "SI accepted unit",
    },
    {
      id: "cubic-centimeters",
      name: "Cubic Centimeters",
      symbol: "cm³",
      factor: 0.001,
      precision: "exact",
      formulaToBase: "value × 0.001",
      source: "By definition: 1 cm³ = 1 mL",
    },
    {
      id: "cubic-meters",
      name: "Cubic Meters",
      symbol: "m³",
      factor: 1000,
      precision: "exact",
      formulaToBase: "value × 1000",
      source: "SI derived unit",
    },
    {
      id: "cubic-feet",
      name: "Cubic Feet",
      symbol: "ft³",
      factor: 28.316846592,
      precision: "exact",
      formulaToBase: "value × 28.316846592",
      source: "International foot definition",
    },
    {
      id: "cubic-yards",
      name: "Cubic Yards",
      symbol: "yd³",
      factor: 764.554857984,
      precision: "exact",
      formulaToBase: "value × 764.554857984",
      source: "International yard definition",
    },
    {
      id: "us-teaspoons",
      name: "US Teaspoons",
      symbol: "tsp (US)",
      factor: 0.00492892159375,
      precision: "exact",
      formulaToBase: "value × 0.00492892159375",
      source: "US customary system",
    },
    {
      id: "us-tablespoons",
      name: "US Tablespoons",
      symbol: "tbsp (US)",
      factor: 0.01478676478125,
      precision: "exact",
      formulaToBase: "value × 0.01478676478125",
      source: "US customary system",
    },
    {
      id: "us-cups",
      name: "US Cups",
      symbol: "cup (US)",
      factor: 0.2365882365,
      precision: "exact",
      formulaToBase: "value × 0.2365882365",
      source: "US customary system",
    },
    {
      id: "us-fluid-ounces",
      name: "US Fluid Ounces",
      symbol: "fl oz (US)",
      factor: 0.0295735295625,
      precision: "exact",
      formulaToBase: "value × 0.0295735295625",
      source: "US customary system",
    },
    {
      id: "us-pints",
      name: "US Pints",
      symbol: "pt (US)",
      factor: 0.473176473,
      precision: "exact",
      formulaToBase: "value × 0.473176473",
      source: "US customary system",
    },
    {
      id: "us-quarts",
      name: "US Quarts",
      symbol: "qt (US)",
      factor: 0.946352946,
      precision: "exact",
      formulaToBase: "value × 0.946352946",
      source: "US customary system",
    },
    {
      id: "us-gallons",
      name: "US Gallons",
      symbol: "gal (US)",
      factor: 3.785411784,
      precision: "exact",
      formulaToBase: "value × 3.785411784",
      source: "US customary system",
    },
    {
      id: "us-dry-gallons",
      name: "US Dry Gallons",
      symbol: "dry gal (US)",
      factor: 4.40488377086,
      precision: "approximate",
      formulaToBase: "value × 4.40488377086",
      source: "US dry measure definition",
    },
    {
      id: "imperial-fluid-ounces",
      name: "Imperial Fluid Ounces",
      symbol: "fl oz (Imp)",
      factor: 0.0284130625,
      precision: "exact",
      formulaToBase: "value × 0.0284130625",
      source: "Imperial system definition",
    },
    {
      id: "imperial-pints",
      name: "Imperial Pints",
      symbol: "pt (Imp)",
      factor: 0.56826125,
      precision: "exact",
      formulaToBase: "value × 0.56826125",
      source: "Imperial system definition",
    },
    {
      id: "imperial-gallons",
      name: "Imperial Gallons",
      symbol: "gal (Imp)",
      factor: 4.54609,
      precision: "exact",
      formulaToBase: "value × 4.54609",
      source: "Imperial Gallon Act, 1824",
    },
    {
      id: "oil-barrels",
      name: "Oil Barrels",
      symbol: "bbl",
      factor: 158.987294928,
      precision: "exact",
      formulaToBase: "value × 158.987294928",
      source: "By definition: 1 bbl = 42 US gallons",
    },
  ],
};
