import type { Category } from "@/lib/types";

export const volume: Category = {
  id: "volume",
  name: "Volume & Capacity",
  icon: "🧊",
  baseUnitId: "liters",
  units: [
    {
      id: "milliliters",
      name: "Millilitres",
      symbol: "mL",
      factor: 0.001,
      precision: "exact",
      formulaToBase: "value × 0.001",
      source: "SI definition",
    },
    {
      id: "liters",
      name: "Litres",
      symbol: "L",
      factor: 1,
      precision: "exact",
      formulaToBase: "value × 1",
      source: "SI accepted unit",
    },
    {
      id: "cubic-centimeters",
      name: "Cubic Centimetres",
      symbol: "cm³",
      factor: 0.001,
      precision: "exact",
      formulaToBase: "value × 0.001",
      source: "By definition: 1 cm³ = 1 mL",
    },
    {
      id: "cubic-meters",
      name: "Cubic Metres",
      symbol: "m³",
      factor: 1000,
      precision: "exact",
      formulaToBase: "value × 1000",
      source: "SI derived unit",
    },
    {
      id: "cubic-feet",
      name: "Cubic Feet",
      symbol: "ft³",
      factor: 28.316846592,
      precision: "exact",
      formulaToBase: "value × 28.316846592",
      source: "International foot definition",
    },
    {
      id: "cubic-yards",
      name: "Cubic Yards",
      symbol: "yd³",
      factor: 764.554857984,
      precision: "exact",
      formulaToBase: "value × 764.554857984",
      source: "International yard definition",
    },
    {
      id: "metric-cups",
      name: "Metric Cups",
      symbol: "cup (metric)",
      factor: 0.25,
      precision: "exact",
      formulaToBase: "value × 0.25",
      source: "Metric definition (250 mL)",
    },
    {
      id: "metric-tablespoons",
      name: "Metric Tablespoons",
      symbol: "tbsp (metric)",
      factor: 0.015,
      precision: "exact",
      formulaToBase: "value × 0.015",
      source: "Metric definition (15 mL)",
    },
    {
      id: "australian-tablespoons",
      name: "Australian Tablespoons",
      symbol: "tbsp (AU)",
      factor: 0.02,
      precision: "exact",
      formulaToBase: "value × 0.02",
      source: "Australian definition (20 mL)",
    },
    {
      id: "metric-teaspoons",
      name: "Metric Teaspoons",
      symbol: "tsp (metric)",
      factor: 0.005,
      precision: "exact",
      formulaToBase: "value × 0.005",
      source: "Metric definition (5 mL)",
    },
    {
      id: "us-teaspoons",
      name: "US Teaspoons",
      symbol: "tsp (US)",
      factor: 0.00492892159375,
      precision: "exact",
      formulaToBase: "value × 0.00492892159375",
      source: "US customary system",
    },
    {
      id: "us-tablespoons",
      name: "US Tablespoons",
      symbol: "tbsp (US)",
      factor: 0.01478676478125,
      precision: "exact",
      formulaToBase: "value × 0.01478676478125",
      source: "US customary system",
    },
    {
      id: "us-cups",
      name: "US Cups",
      symbol: "cup (US)",
      factor: 0.2365882365,
      precision: "exact",
      formulaToBase: "value × 0.2365882365",
      source: "US customary system",
    },
    {
      id: "us-fluid-ounces",
      name: "US Fluid Ounces",
      symbol: "fl oz (US)",
      factor: 0.0295735295625,
      precision: "exact",
      formulaToBase: "value × 0.0295735295625",
      source: "US customary system",
    },
    {
      id: "us-pints",
      name: "US Pints",
      symbol: "pt (US)",
      factor: 0.473176473,
      precision: "exact",
      formulaToBase: "value × 0.473176473",
      source: "US customary system",
    },
    {
      id: "us-quarts",
      name: "US Quarts",
      symbol: "qt (US)",
      factor: 0.946352946,
      precision: "exact",
      formulaToBase: "value × 0.946352946",
      source: "US customary system",
    },
    {
      id: "us-gallons",
      name: "US Gallons",
      symbol: "gal (US)",
      factor: 3.785411784,
      precision: "exact",
      formulaToBase: "value × 3.785411784",
      source: "US customary system",
    },
    {
      id: "us-dry-gallons",
      name: "US Dry Gallons",
      symbol: "dry gal (US)",
      factor: 4.40488377086,
      precision: "approximate",
      formulaToBase: "value × 4.40488377086",
      source: "US dry measure definition",
    },
    {
      id: "imperial-fluid-ounces",
      name: "Imperial Fluid Ounces",
      symbol: "fl oz (Imp)",
      factor: 0.0284130625,
      precision: "exact",
      formulaToBase: "value × 0.0284130625",
      source: "Imperial system definition",
    },
    {
      id: "imperial-pints",
      name: "Imperial Pints",
      symbol: "pt (Imp)",
      factor: 0.56826125,
      precision: "exact",
      formulaToBase: "value × 0.56826125",
      source: "Imperial system definition",
    },
    {
      id: "imperial-quarts",
      name: "Imperial Quarts",
      symbol: "qt (Imp)",
      factor: 1.1365225,
      precision: "exact",
      formulaToBase: "value × 1.1365225",
      source: "Imperial system definition",
    },
    {
      id: "imperial-gallons",
      name: "Imperial Gallons",
      symbol: "gal (Imp)",
      factor: 4.54609,
      precision: "exact",
      formulaToBase: "value × 4.54609",
      source: "Imperial Gallon Act, 1824",
    },
    {
      id: "oil-barrels",
      name: "Oil Barrels",
      symbol: "bbl",
      factor: 158.987294928,
      precision: "exact",
      formulaToBase: "value × 158.987294928",
      source: "By definition: 1 bbl = 42 US gallons",
    },
    {
      id: "imperial-cups",
      name: "Imperial Cups",
      symbol: "cup (Imp)",
      factor: 0.284130625,
      precision: "exact",
      formulaToBase: "value × 0.284130625",
      source: "Imperial: 1 cup = 10 fl oz (Imp)",
    },
    {
      id: "imperial-tablespoons",
      name: "Imperial Tablespoons",
      symbol: "tbsp (Imp)",
      factor: 0.0177581640625,
      precision: "exact",
      formulaToBase: "value × 0.0177581640625",
      source: "Imperial: 1 tbsp = 5/8 fl oz (Imp)",
    },
    {
      id: "imperial-teaspoons",
      name: "Imperial Teaspoons",
      symbol: "tsp (Imp)",
      factor: 0.00591938802083,
      precision: "approximate",
      formulaToBase: "value × 0.00591938802083",
      source: "Imperial: 1 tsp = 1/3 tbsp (Imp)",
    },
    {
      id: "japanese-go",
      name: "Japanese Gō",
      symbol: "gō",
      factor: 0.18039,
      precision: "approximate",
      formulaToBase: "value × 0.18039",
      source: "Japanese traditional volume: 1 gō ≈ 180.39 mL",
    },
  ],
};
